### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by zer0Kerbal** [Li0n-0/Antenna-Helper#47]
Would have put this in @linuxgurugamer's repo - but issues/ discussions not implemented.

CustomBarnKit (CBK) allows for more than three levels of tracking station. Strategia, Bureaucracy and Komplexity (and more) make use of this.

Would you enhance this wonderful mod to look for and use additional levels of Tracking Station?

**Comment by linuxgurugamer** [comment]
It's there now, go ahead and copy this there.  No idea what it would entail at this point
